GET http://localhost:3003

###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Osmar Santos",
    "email": "osmarsantos@gmail.com",
    "password": "Bia358764"
}