GET http://localhost:3003

###
POST http://localhost:3003/actor
Content-Type: application/json

{
    "name": "Emma Watson",
    "salary": 1000000,
    "birth_date": "1994-08-25",
    "gender": "female",
    "hometown": "United States"
}